### ISSUE TITLE
Allow FSxN provisioning without ONTAP Cloud credentials

### ISSUE THREAD

**Issue by badnetmask** [ansible-collections/netapp.cloudmanager#6]
### Summary

First of all, thank you for providing the `netapp.cloudmanager.na_cloudmanager_aws_fsx` module.It really looks very handy.

However it seems like this module requires that we present credentials to associate the newly created filesystem with an ONTAP Cloud account. While I understand this makes sense from a NetApp perspective, as a vendor, some people (like me) may would like to try to use this product in a test/development environment, without necessarily connecting with an account.

Would it be possible to remove the ONTAP Cloud account requirement? I know it's possible to use without it because I can create a new filesystem using the AWS web interface, but I would like to do the same via Ansible.

Thank you.

### Component Name

netapp.cloudmanager.na_cloudmanager_aws_fsx

### Additional Information

```
No playbook available at this time.
```

**Comment by lonico** [comment]
Thank you for your interest,
Unfortunately, this is not possible, as we are using Cloud Manager APIs to create the FSxN instance.  These APIs are different than the APIs AWS is using.

I was not able to find a native AWS collection that supports FSx, but if you can use Terraform, there are 2 providers:
- ours, with the same requirement on Cloud Manager: https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/latest
- AWS, that supports FSxN: https://registry.terraform.io/providers/hashicorp/aws/latest

**Comment by badnetmask** [comment]
Sad, but I understand. Thanks for responding so quick.
